### ISSUE TITLE
Voila doesn't load static HTML files despite whitelisting

### ISSUE THREAD

**Issue by tilusnet** [voila-dashboards/voila#1071]
Following up the conversation in https://github.com/voila-dashboards/voila/issues/1044#issuecomment-1019301192:

## Description

My Jupyter notebook loads `ipywidgets` some of them instantiating `IFrame` objects loading static html files.

Despite whitelisting html files in Voila (v0.3.0), the Voila server fails with a 500 error:
```
ERROR:tornado.application:Uncaught exception GET /voila/render/hello.html (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/voila/render/hello.html', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/tilushq/opt/miniconda3/envs/jupyter/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/tilushq/opt/miniconda3/envs/jupyter/lib/python3.7/site-packages/voila/handler.py", line 150, in get
    kernel_name=gen.notebook.metadata.kernelspec.name,
AttributeError: 'NoneType' object has no attribute 'metadata'
ERROR:tornado.access:500 GET /voila/render/hello.html (127.0.0.1) 18.03ms
```

## Reproduce

All files are in working directory X:
* voila.json
* test.ipynb
* hello.html

1. Create a `voila.json` file with configuration:

```json
{
    "VoilaConfiguration": {
        "file_whitelist": [
            ".*\\.(html|js)"
        ]
    }
}
```

2. Create a `test.ipynb` with the minimal code:

```python
hello_file = 'hello.html'
hello_body = '<body><h1>Hello World!</h1></body>'

with open(hello_file, 'w') as fw:
    _ = fw.write(hello_body)
    
from IPython.display import display, display_html, IFrame

my_html_widget = IFrame(
    src=hello_file,
    width=300,
    height=100
)

import ipywidgets as w

widget_output = w.Output()
with widget_output:
    display(my_html_widget)

widget_output
```

3. Invoke Voila in directory X:
`voila .`

4. Open `test.ipynb` in the browser and let it run.

The rendering fails:

![image](https://user-images.githubusercontent.com/705606/150699955-2c42f854-2d11-4aaf-9a5c-70ec5093d472.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/705606/150695046-d48932ee-d22e-4c57-be85-70c36ecd8273.png)

## Context

- voila version 0.3.0
- Operating System and version: Ubuntu 20.04
- Browser and version: Chrome 97
- JupyterLab version: 3

**Comment by tilusnet** [comment]
Hello.

I reran my tests with the newly released 0.3.1 and this bug is not fixed.
