### ISSUE TITLE
Error loading server extension voila.server_extension

### ISSUE THREAD

**Issue by fortinux** [voila-dashboards/voila#1138]
Hi, 
I had problems starting Voilà in a venv (Ubuntu 20.04 OS, LXC virtual machine, Python 3.8). the error was:
 Error loading server extension voila
    Traceback (most recent call last):
      File "/root/jupyterlab/venv/lib/python3.8/site-packages/notebook/notebookapp.py", line 2027, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 848, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/root/jupyterlab/venv/lib/python3.8/site-packages/voila/__init__.py", line 11, in <module>
        from .server_extension import _load_jupyter_server_extension # noqa
      File "/root/jupyterlab/venv/lib/python3.8/site-packages/voila/server_extension.py", line 21, in <module>
        from .handler import VoilaHandler
      File "/root/jupyterlab/venv/lib/python3.8/site-packages/voila/handler.py", line 24, in <module>
        from .notebook_renderer import NotebookRenderer
      File "/root/jupyterlab/venv/lib/python3.8/site-packages/voila/notebook_renderer.py", line 24, in <module>
        from .exporter import VoilaExporter
      File "/root/jupyterlab/venv/lib/python3.8/site-packages/voila/exporter.py", line 15, in <module>
        from jinja2 import contextfilter
    ImportError: cannot import name 'contextfilter' from 'jinja2' (/root/jupyterlab/venv/lib/python3.8/site-packages/jinja2/__init__.py)
[W 10:57:43.630 NotebookApp] Error loading server extension voila.server_extension
    Traceback (most recent call last):
      File "/root/jupyterlab/venv/lib/python3.8/site-packages/notebook/notebookapp.py", line 2027, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 848, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/root/jupyterlab/venv/lib/python3.8/site-packages/voila/__init__.py", line 11, in <module>
        from .server_extension import _load_jupyter_server_extension # noqa
      File "/root/jupyterlab/venv/lib/python3.8/site-packages/voila/server_extension.py", line 21, in <module>
        from .handler import VoilaHandler
      File "/root/jupyterlab/venv/lib/python3.8/site-packages/voila/handler.py", line 24, in <module>
        from .notebook_renderer import NotebookRenderer
      File "/root/jupyterlab/venv/lib/python3.8/site-packages/voila/notebook_renderer.py", line 24, in <module>
        from .exporter import VoilaExporter
      File "/root/jupyterlab/venv/lib/python3.8/site-packages/voila/exporter.py", line 15, in <module>
        from jinja2 import contextfilter
    ImportError: cannot import name 'contextfilter' from 'jinja2' (/root/jupyterlab/venv/lib/python3.8/site-packages/jinja2/__init__.py)

My solution was to edit the following lines at /root/jupyterlab/venv/lib/python3.8/site-packages/voila/exporter.py 

```
# from jinja2 import contextfilter
from jinja2 import pass_context

    # @contextfilter
    @pass_context
```
Since contextfilter and contextfuncion were replaced: https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.runtime.Context

Hope it can help anyone with the same problem as me.
Thanks

**Comment by martinRenou** [comment]
Thanks for reporting, please update to Voila 0.3.5
