### ISSUE TITLE
Support jupyter-client 7.4.4 or upcoming v8 in voila 0.5

### ISSUE THREAD

**Issue by bnavigator** [voila-dashboards/voila#1253]
Thanks a lot everyone for investigating! It looks like `jupyter_client 7.4.2` was indeed the culprit, we will have [an upper-bound for now](https://github.com/voila-dashboards/voila/pull/1239) and release 0.4.0.

_Originally posted by @martinRenou in https://github.com/voila-dashboards/voila/issues/1234#issuecomment-1290304936_

Please fix the incompatibility with recent jupyter-client before releasing 0.5

**Comment by bnavigator** [comment]
Still an issue with jupyter_client 7.4.8

**Comment by bnavigator** [comment]
Somehow this is no longer a problem with 7.4.8. Some underlying dependency must have fixed it.

**Comment by martinRenou** [comment]
Thanks for posting an update! We can probably change the pinning for 0.5.0 then

**Comment by bnavigator** [comment]
I spoke too soon. My check was not thorough enough, the failure is flaky.

In the latest run, the tests pass for Python 3.8, and then hang on 3.9:

https://build.opensuse.org/package/show/devel:languages:python:jupyter/python-voila  -> python-voila:test / openSUSE Tumbleweed / x86_64

```
[   50s] + python_flavor=python38
[   50s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-voila-test-0.4.0-66.1.x86_64/usr/lib/python3.8/site-packages
[   50s] + PYTHONDONTWRITEBYTECODE=1
[   50s] + pytest-3.8 --ignore=_build.python38 --ignore=_build.python39 --ignore=_build.python310 -v tests -k 'not (test_kernel_death or test_request_with_query)' --reruns 2 --reruns-delay 1
[   51s] ============================= test session starts ==============================
[   51s] platform linux -- Python 3.8.16, pytest-7.1.2, pluggy-1.0.0 -- /usr/bin/python3.8
[   51s] cachedir: .pytest_cache
[   51s] rootdir: /home/abuild/rpmbuild/BUILD/voila-0.4.0
[   51s] plugins: anyio-3.6.2, rerunfailures-10.2, tornasync-0.6.0.post2
[   53s] collecting ... collected 73 items / 6 deselected / 67 selected
[   53s] 
[   56s] tests/execute_output_test.py::test_execute_output PASSED                 [  1%]
[   57s] tests/app/config_paths_test.py::test_config_app PASSED                   [  2%]
[   58s] tests/app/config_paths_test.py::test_config_kernel_manager PASSED        [  4%]
[   59s] tests/app/config_paths_test.py::test_config_contents_manager PASSED      [  5%]
[   60s] tests/app/config_paths_test.py::test_template PASSED                     [  7%]
[   63s] tests/app/cwd_subdir_test.py::test_hello_world PASSED                    [  8%]
[   66s] tests/app/cwd_test.py::test_template_cwd PASSED                          [ 10%]
[   66s] tests/app/execute_cpp_test.py::test_non_existing_kernel SKIPPED (opt...) [ 11%]
[   69s] tests/app/execute_test.py::test_hello_world PASSED                       [ 13%]
[   72s] tests/app/execute_test.py::test_no_execute_allowed PASSED                [ 14%]
[   75s] tests/app/image_inlining_test.py::test_image_inlining PASSED             [ 16%]
[   79s] tests/app/many_iopub_messages_test.py::test_template_cwd PASSED          [ 17%]
[   81s] tests/app/nbextensions_test.py::test_lists_extension PASSED              [ 19%]
[   84s] tests/app/no_kernelspec_test.py::test_non_existing_kernel PASSED         [ 20%]
[   87s] tests/app/no_strip_sources_test.py::test_no_strip_sources PASSED         [ 22%]
[   90s] tests/app/non_existing_kernel_test.py::test_non_existing_kernel PASSED   [ 23%]
[   95s] tests/app/notebooks_test.py::test_other_comms PASSED                     [ 25%]
[  103s] tests/app/preheat_activation_test.py::test_request_before_kernel_heated PASSED [ 26%]
[  112s] tests/app/preheat_activation_test.py::test_render_time_with_preheated_kernel PASSED [ 28%]
[  124s] tests/app/preheat_activation_test.py::test_render_time_with_multiple_requests PASSED [ 29%]
[  138s] tests/app/preheat_activation_test.py::test_request_with_theme_parameter PASSED [ 31%]
[  144s] tests/app/preheat_activation_test.py::test_request_with_template_parameter PASSED [ 32%]
[  168s] tests/app/preheat_configuration_test.py::test_refill_kernel_asynchronously PASSED [ 34%]
[  181s] tests/app/preheat_configuration_test.py::test_env_variable_defined_in_kernel PASSED [ 35%]
[  186s] tests/app/preheat_default_kernel_env_test.py::test_default_kernel_env_variable PASSED [ 37%]
[  199s] tests/app/preheat_multiple_notebooks_test.py::test_render_notebook_with_heated_kernel PASSED [ 38%]
[  215s] tests/app/preheat_multiple_notebooks_test.py::test_render_blacklisted_notebook_with_nornal_kernel PASSED [ 40%]
[  218s] tests/app/prelaunch_hook_papermill_test.py::test_prelaunch_hook_papermill PASSED [ 41%]
[  221s] tests/app/prelaunch_hook_test.py::test_prelaunch_hook PASSED             [ 43%]
[  224s] tests/app/preprocessor_test.py::test_markdown_preprocessor PASSED        [ 44%]
[  227s] tests/app/serve_directory_test.py::test_print PASSED                     [ 46%]
[  230s] tests/app/serve_directory_test.py::test_print_py PASSED                  [ 47%]
[  230s] tests/app/serve_directory_test.py::test_print_julia_notebook SKIPPED     [ 49%]
[  232s] tests/app/show_traceback_test.py::test_syntax_error[True] PASSED         [ 50%]
[  235s] tests/app/show_traceback_test.py::test_syntax_error[False] PASSED        [ 52%]
[  238s] tests/app/shutdown_kernel_test.py::test_shutdown_handler PASSED          [ 53%]
[  239s] tests/app/static_files_test.py::test_static_file_absolute_path PASSED    [ 55%]
[  240s] tests/app/static_files_test.py::test_static_file_not_found PASSED        [ 56%]
[  241s] tests/app/static_files_test.py::test_static_file_availability_default PASSED [ 58%]
[  242s] tests/app/static_files_test.py::test_static_file_override PASSED         [ 59%]
[  243s] tests/app/static_files_test.py::test_static_file_other_template PASSED   [ 61%]
[  246s] tests/app/syntax_error_test.py::test_syntax_error PASSED                 [ 62%]
[  248s] tests/app/template_arg_test.py::test_template PASSED                     [ 64%]
[  249s] tests/app/template_cli_test.py::test_template_test PASSED                [ 65%]
[  250s] tests/app/template_config_file_test.py::test_template_test PASSED        [ 67%]
[  251s] tests/app/template_custom_test.py::test_template PASSED                  [ 68%]
[  254s] tests/app/template_sanity_test.py::test_lists_extension[lab] PASSED      [ 70%]
[  257s] tests/app/template_sanity_test.py::test_lists_extension[classic] PASSED  [ 71%]
[  261s] tests/app/timeout_test.py::test_timeout PASSED                           [ 73%]
[  262s] tests/app/tree_test.py::test_tree PASSED                                 [ 74%]
[  264s] tests/server/cwd_subdir_test.py::test_hello_world PASSED                 [ 76%]
[  264s] tests/server/execute_cpp_test.py::test_non_existing_kernel SKIPPED (...) [ 77%]
[  267s] tests/server/execute_test.py::test_hello_world PASSED                    [ 79%]
[  270s] tests/server/nbextensions_test.py::test_lists_extension XFAIL (needs...) [ 80%]
[  273s] tests/server/no_strip_sources_test.py::test_hello_world PASSED           [ 82%]
[  275s] tests/server/show_traceback_test.py::test_syntax_error[True] PASSED      [ 83%]
[  278s] tests/server/show_traceback_test.py::test_syntax_error[False] PASSED     [ 85%]
[  279s] tests/server/static_files_test.py::test_static_file_absolute_path PASSED [ 86%]
[  280s] tests/server/static_files_test.py::test_static_file_not_found PASSED     [ 88%]
[  282s] tests/server/static_files_test.py::test_static_file_availability_default PASSED [ 89%]
[  283s] tests/server/static_files_test.py::test_static_file_override PASSED      [ 91%]
[  284s] tests/server/static_files_test.py::test_static_file_other_template PASSED [ 92%]
[  285s] tests/server/tree_test.py::test_tree PASSED                              [ 94%]
[  286s] tests/template_prefixes/loader_test.py::test_loader_default_nbconvert PASSED [ 95%]
[  287s] tests/template_prefixes/loader_test.py::test_loader_foo PASSED           [ 97%]
[  288s] tests/template_prefixes/loader_test.py::test_loader_bar_voila PASSED     [ 98%]
[  289s] tests/template_prefixes/loader_test.py::test_loader_bar_nbconvert PASSED [100%]
[  289s] 
[  289s] =============================== warnings summary ===============================
[  289s] tests/app/config_paths_test.py::test_config_app
[  289s] tests/app/config_paths_test.py::test_config_kernel_manager
[  289s] tests/app/config_paths_test.py::test_config_contents_manager
[  289s] tests/app/config_paths_test.py::test_template
[  289s]   /usr/lib/python3.8/site-packages/traitlets/traitlets.py:2773: FutureWarning: --Voila.config_file_paths=['/home/abuild/rpmbuild/BUILD/voila-0.4.0/tests/app/../configs/general'] for containers is deprecated in traitlets 5.0. You can pass `--Voila.config_file_paths item` ... multiple times to add items to a list.
[  289s]     warn(
[  289s] 
[  289s] tests/app/config_paths_test.py: 1 warning
[  289s] tests/app/cwd_subdir_test.py: 1 warning
[  289s] tests/app/cwd_test.py: 1 warning
[  289s] tests/app/execute_test.py: 2 warnings
[  289s] tests/app/image_inlining_test.py: 1 warning
[  289s] tests/app/nbextensions_test.py: 1 warning
[  289s] tests/app/no_kernelspec_test.py: 1 warning
[  289s] tests/app/no_strip_sources_test.py: 1 warning
[  289s] tests/app/non_existing_kernel_test.py: 1 warning
[  289s] tests/app/notebooks_test.py: 1 warning
[  289s] tests/app/preheat_activation_test.py: 5 warnings
[  289s] tests/app/preheat_configuration_test.py: 2 warnings
[  289s] tests/app/preheat_default_kernel_env_test.py: 1 warning
[  289s] tests/app/preheat_multiple_notebooks_test.py: 2 warnings
[  289s] tests/app/prelaunch_hook_papermill_test.py: 1 warning
[  289s] tests/app/prelaunch_hook_test.py: 1 warning
[  289s] tests/app/preprocessor_test.py: 1 warning
[  289s] tests/app/serve_directory_test.py: 2 warnings
[  289s] tests/app/show_traceback_test.py: 2 warnings
[  289s] tests/app/shutdown_kernel_test.py: 1 warning
[  289s] tests/app/static_files_test.py: 5 warnings
[  289s] tests/app/syntax_error_test.py: 1 warning
[  289s] tests/app/template_arg_test.py: 1 warning
[  289s] tests/app/template_cli_test.py: 1 warning
[  289s] tests/app/template_config_file_test.py: 1 warning
[  289s] tests/app/template_custom_test.py: 1 warning
[  289s] tests/app/template_sanity_test.py: 2 warnings
[  289s] tests/app/timeout_test.py: 1 warning
[  289s] tests/app/tree_test.py: 1 warning
[  289s] tests/server/cwd_subdir_test.py: 1 warning
[  289s] tests/server/execute_test.py: 1 warning
[  289s] tests/server/nbextensions_test.py: 1 warning
[  289s] tests/server/no_strip_sources_test.py: 1 warning
[  289s] tests/server/show_traceback_test.py: 2 warnings
[  289s]   /usr/lib64/python3.8/site-packages/tornado/ioloop.py:350: DeprecationWarning: make_current is deprecated; start the event loop first
[  289s]     self.make_current()
[  289s] 
[  289s] tests/app/config_paths_test.py: 1 warning
[  289s] tests/app/cwd_subdir_test.py: 1 warning
[  289s] tests/app/cwd_test.py: 1 warning
[  289s] tests/app/execute_test.py: 2 warnings
[  289s] tests/app/image_inlining_test.py: 1 warning
[  289s] tests/app/nbextensions_test.py: 1 warning
[  289s] tests/app/no_kernelspec_test.py: 1 warning
[  289s] tests/app/no_strip_sources_test.py: 1 warning
[  289s] tests/app/non_existing_kernel_test.py: 1 warning
[  289s] tests/app/notebooks_test.py: 1 warning
[  289s] tests/app/preheat_activation_test.py: 5 warnings
[  289s] tests/app/preheat_configuration_test.py: 2 warnings
[  289s] tests/app/preheat_default_kernel_env_test.py: 1 warning
[  289s] tests/app/preheat_multiple_notebooks_test.py: 2 warnings
[  289s] tests/app/prelaunch_hook_papermill_test.py: 1 warning
[  289s] tests/app/prelaunch_hook_test.py: 1 warning
[  289s] tests/app/preprocessor_test.py: 1 warning
[  289s] tests/app/serve_directory_test.py: 2 warnings
[  289s] tests/app/show_traceback_test.py: 2 warnings
[  289s] tests/app/shutdown_kernel_test.py: 1 warning
[  289s] tests/app/static_files_test.py: 5 warnings
[  289s] tests/app/syntax_error_test.py: 1 warning
[  289s] tests/app/template_arg_test.py: 1 warning
[  289s] tests/app/template_cli_test.py: 1 warning
[  289s] tests/app/template_config_file_test.py: 1 warning
[  289s] tests/app/template_custom_test.py: 1 warning
[  289s] tests/app/template_sanity_test.py: 2 warnings
[  289s] tests/app/timeout_test.py: 1 warning
[  289s] tests/app/tree_test.py: 1 warning
[  289s] tests/server/cwd_subdir_test.py: 1 warning
[  289s] tests/server/execute_test.py: 1 warning
[  289s] tests/server/nbextensions_test.py: 1 warning
[  289s] tests/server/no_strip_sources_test.py: 1 warning
[  289s] tests/server/show_traceback_test.py: 2 warnings
[  289s] tests/server/static_files_test.py: 5 warnings
[  289s] tests/server/tree_test.py: 1 warning
[  289s]   /usr/lib/python3.8/site-packages/pytest_tornasync/plugin.py:65: DeprecationWarning: make_current is deprecated; start the event loop first
[  289s]     loop.make_current()
[  289s] 
[  289s] tests/app/config_paths_test.py: 1 warning
[  289s] tests/app/cwd_subdir_test.py: 1 warning
[  289s] tests/app/cwd_test.py: 1 warning
[  289s] tests/app/execute_test.py: 2 warnings
[  289s] tests/app/image_inlining_test.py: 1 warning
[  289s] tests/app/nbextensions_test.py: 1 warning
[  289s] tests/app/no_kernelspec_test.py: 1 warning
[  289s] tests/app/no_strip_sources_test.py: 1 warning
[  289s] tests/app/non_existing_kernel_test.py: 1 warning
[  289s] tests/app/notebooks_test.py: 1 warning
[  289s] tests/app/preheat_activation_test.py: 5 warnings
[  289s] tests/app/preheat_configuration_test.py: 2 warnings
[  289s] tests/app/preheat_default_kernel_env_test.py: 1 warning
[  289s] tests/app/preheat_multiple_notebooks_test.py: 2 warnings
[  289s] tests/app/prelaunch_hook_papermill_test.py: 1 warning
[  289s] tests/app/prelaunch_hook_test.py: 1 warning
[  289s] tests/app/preprocessor_test.py: 1 warning
[  289s] tests/app/serve_directory_test.py: 2 warnings
[  289s] tests/app/show_traceback_test.py: 2 warnings
[  289s] tests/app/shutdown_kernel_test.py: 1 warning
[  289s] tests/app/static_files_test.py: 5 warnings
[  289s] tests/app/syntax_error_test.py: 1 warning
[  289s] tests/app/template_arg_test.py: 1 warning
[  289s] tests/app/template_cli_test.py: 1 warning
[  289s] tests/app/template_config_file_test.py: 1 warning
[  289s] tests/app/template_custom_test.py: 1 warning
[  289s] tests/app/template_sanity_test.py: 2 warnings
[  289s] tests/app/timeout_test.py: 1 warning
[  289s] tests/app/tree_test.py: 1 warning
[  289s] tests/server/cwd_subdir_test.py: 1 warning
[  289s] tests/server/execute_test.py: 1 warning
[  289s] tests/server/nbextensions_test.py: 1 warning
[  289s] tests/server/no_strip_sources_test.py: 1 warning
[  289s] tests/server/show_traceback_test.py: 2 warnings
[  289s] tests/server/static_files_test.py: 5 warnings
[  289s] tests/server/tree_test.py: 1 warning
[  289s]   /usr/lib/python3.8/site-packages/pytest_tornasync/plugin.py:67: DeprecationWarning: clear_current is deprecated
[  289s]     loop.clear_current()
[  289s] 
[  289s] tests/app/cwd_subdir_test.py::test_hello_world
[  289s] tests/app/no_kernelspec_test.py::test_non_existing_kernel
[  289s] tests/app/non_existing_kernel_test.py::test_non_existing_kernel
[  289s] tests/app/notebooks_test.py::test_other_comms
[  289s] tests/app/serve_directory_test.py::test_print
[  289s] tests/app/serve_directory_test.py::test_print_py
[  289s] tests/app/show_traceback_test.py::test_syntax_error[True]
[  289s] tests/app/show_traceback_test.py::test_syntax_error[False]
[  289s] tests/app/tree_test.py::test_tree
[  289s]   /usr/lib/python3.8/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/abuild/rpmbuild/BUILD/voila-0.4.0/tests/notebooks' instead of "'/home/abuild/rpmbuild/BUILD/voila-0.4.0/tests/notebooks'" if you require traitlets >=5.
[  289s]     warn(
[  289s] 
[  289s] tests/app/cwd_test.py: 1 warning
[  289s] tests/app/execute_test.py: 2 warnings
[  289s] tests/app/image_inlining_test.py: 1 warning
[  289s] tests/app/no_strip_sources_test.py: 1 warning
[  289s] tests/app/preheat_activation_test.py: 5 warnings
[  289s] tests/app/preheat_default_kernel_env_test.py: 1 warning
[  289s] tests/app/prelaunch_hook_papermill_test.py: 1 warning
[  289s] tests/app/prelaunch_hook_test.py: 1 warning
[  289s] tests/app/preprocessor_test.py: 1 warning
[  289s] tests/app/shutdown_kernel_test.py: 1 warning
[  289s] tests/app/static_files_test.py: 5 warnings
[  289s] tests/app/syntax_error_test.py: 1 warning
[  289s] tests/app/template_arg_test.py: 1 warning
[  289s] tests/app/template_cli_test.py: 1 warning
[  289s] tests/app/template_config_file_test.py: 1 warning
[  289s] tests/app/template_custom_test.py: 1 warning
[  289s] tests/app/template_sanity_test.py: 2 warnings
[  289s] tests/app/timeout_test.py: 1 warning
[  289s]   /usr/lib/python3.8/site-packages/traitlets/traitlets.py:2773: FutureWarning: --Voila.config_file_paths=[] for containers is deprecated in traitlets 5.0. You can pass `--Voila.config_file_paths item` ... multiple times to add items to a list.
[  289s]     warn(
[  289s] 
[  289s] tests/app/execute_test.py::test_no_execute_allowed
[  289s]   /usr/lib/python3.8/site-packages/jupyter_server/base/handlers.py:197: UserWarning: The Tornado web application does not have an 'authorizer' defined in its settings. In future releases of jupyter_server, this will be a required key for all subclasses of `JupyterHandler`. For an example, see the jupyter_server source code for how to add an authorizer to the tornado settings: https://github.com/jupyter-server/jupyter_server/blob/653740cbad7ce0c8a8752ce83e4d3c2c754b13cb/jupyter_server/serverapp.py#L234-L256
[  289s]     warnings.warn(
[  289s] 
[  289s] tests/app/nbextensions_test.py::test_lists_extension
[  289s]   /usr/lib/python3.8/site-packages/traitlets/traitlets.py:2773: FutureWarning: --Voila.config_file_paths=['/home/abuild/rpmbuild/BUILD/voila-0.4.0/tests/configs/general'] for containers is deprecated in traitlets 5.0. You can pass `--Voila.config_file_paths item` ... multiple times to add items to a list.
[  289s]     warn(
[  289s] 
[  289s] tests/app/preheat_configuration_test.py::test_refill_kernel_asynchronously
[  289s] tests/app/preheat_configuration_test.py::test_env_variable_defined_in_kernel
[  289s] tests/app/preheat_multiple_notebooks_test.py::test_render_notebook_with_heated_kernel
[  289s] tests/app/preheat_multiple_notebooks_test.py::test_render_blacklisted_notebook_with_nornal_kernel
[  289s]   /usr/lib/python3.8/site-packages/traitlets/traitlets.py:2773: FutureWarning: --Voila.config_file_paths=['/home/abuild/rpmbuild/BUILD/voila-0.4.0/tests/app/../configs/preheat'] for containers is deprecated in traitlets 5.0. You can pass `--Voila.config_file_paths item` ... multiple times to add items to a list.
[  289s]     warn(
[  289s] 
[  289s] tests/app/preheat_default_kernel_env_test.py::test_default_kernel_env_variable
[  289s]   /usr/lib/python3.8/site-packages/traitlets/traitlets.py:3278: FutureWarning: --default_env_variables={"FOO": "BAR"} for dict-traits is deprecated in traitlets 5.0. You can pass --default_env_variables <key=value> ... multiple times to add items to a dict.
[  289s]     warn(
[  289s] 
[  289s] tests/app/prelaunch_hook_papermill_test.py::test_prelaunch_hook_papermill
[  289s]   /usr/lib/python3.8/site-packages/nbformat/__init__.py:92: MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
[  289s]     validate(nb)
[  289s] 
[  289s] tests/app/prelaunch_hook_papermill_test.py::test_prelaunch_hook_papermill
[  289s]   /usr/lib/python3.8/site-packages/ansiwrap/core.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
[  289s]     import imp
[  289s] 
[  289s] tests/app/serve_directory_test.py::test_print
[  289s] tests/app/serve_directory_test.py::test_print_py
[  289s]   /usr/lib/python3.8/site-packages/traitlets/traitlets.py:3278: FutureWarning: --extension_language_mapping={".py": "python"} for dict-traits is deprecated in traitlets 5.0. You can pass --extension_language_mapping <key=value> ... multiple times to add items to a dict.
[  289s]     warn(
[  289s] 
[  289s] tests/app/template_cli_test.py::test_template_test
[  289s]   /usr/lib/python3.8/site-packages/traitlets/traitlets.py:2773: FutureWarning: --Voila.template_paths=['/home/abuild/rpmbuild/BUILD/voila-0.4.0/tests/test_template/share/jupyter/voila/templates/test_template', '/home/abuild/rpmbuild/BUILD/voila-0.4.0/share/jupyter/voila/templates/default'] for containers is deprecated in traitlets 5.0. You can pass `--Voila.template_paths item` ... multiple times to add items to a list.
[  289s]     warn(
[  289s] 
[  289s] tests/app/tree_test.py::test_tree
[  289s] tests/server/tree_test.py::test_tree
[  289s]   /usr/lib/python3.8/site-packages/traitlets/traitlets.py:3278: FutureWarning: --extension_language_mapping={".xcpp": "C++11"} for dict-traits is deprecated in traitlets 5.0. You can pass --extension_language_mapping <key=value> ... multiple times to add items to a dict.
[  289s]     warn(
[  289s] 
[  289s] -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
[  289s] = 63 passed, 3 skipped, 6 deselected, 1 xfailed, 214 warnings in 237.55s (0:03:57) =
[  289s] --- Logging error ---
[  289s] Traceback (most recent call last):
[  289s]   File "/usr/lib64/python3.8/logging/__init__.py", line 1088, in emit
[  289s]     stream.write(msg + self.terminator)
[  289s] ValueError: I/O operation on closed file.
[  289s] Call stack:
[  289s]   File "/usr/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 122, in __del__
[  289s]     self.log.debug("Destroying zmq context for %s", self)
[  289s] Message: 'Destroying zmq context for %s'
[  289s] Arguments: (<jupyter_server.services.kernels.kernelmanager.AsyncMappingKernelManager object at 0x7fec90f14550>,)
[  289s] --- Logging error ---
[  289s] Traceback (most recent call last):
[  289s]   File "/usr/lib64/python3.8/logging/__init__.py", line 1088, in emit
[  289s]     stream.write(msg + self.terminator)
[  289s] ValueError: I/O operation on closed file.
[  289s] Call stack:
[  289s]   File "/usr/lib/python3.8/site-packages/jupyter_client/client.py", line 128, in __del__
[  289s]     self.log.debug("Destroying zmq context for %s", self)
[  289s] Message: 'Destroying zmq context for %s'
[  289s] Arguments: (<jupyter_client.asynchronous.client.AsyncKernelClient object at 0x7fec90ed42b0>,)
[  289s] --- Logging error ---
[  289s] Traceback (most recent call last):
[  289s]   File "/usr/lib64/python3.8/logging/__init__.py", line 1088, in emit
[  289s]     stream.write(msg + self.terminator)
[  289s] ValueError: I/O operation on closed file.
[  289s] Call stack:
[  289s]   File "/usr/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 122, in __del__
[  289s]     self.log.debug("Destroying zmq context for %s", self)
[  289s] Message: 'Destroying zmq context for %s'
[  289s] Arguments: (<jupyter_server.services.kernels.kernelmanager.AsyncMappingKernelManager object at 0x7fec90baa070>,)
[  289s] --- Logging error ---
[  289s] Traceback (most recent call last):
[  289s]   File "/usr/lib64/python3.8/logging/__init__.py", line 1088, in emit
[  289s]     stream.write(msg + self.terminator)
[  289s] ValueError: I/O operation on closed file.
[  289s] Call stack:
[  289s]   File "/usr/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 122, in __del__
[  289s]     self.log.debug("Destroying zmq context for %s", self)
[  289s] Message: 'Destroying zmq context for %s'
[  289s] Arguments: (<jupyter_server.services.kernels.kernelmanager.AsyncMappingKernelManager object at 0x7fec90b8e070>,)
[  289s] --- Logging error ---
[  289s] Traceback (most recent call last):
[  289s]   File "/usr/lib64/python3.8/logging/__init__.py", line 1088, in emit
[  289s]     stream.write(msg + self.terminator)
[  289s] ValueError: I/O operation on closed file.
[  289s] Call stack:
[  289s]   File "/usr/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 122, in __del__
[  289s]     self.log.debug("Destroying zmq context for %s", self)
[  289s] Message: 'Destroying zmq context for %s'
[  289s] Arguments: (<jupyter_server.services.kernels.kernelmanager.AsyncMappingKernelManager object at 0x7fec9171aeb0>,)
[  289s] --- Logging error ---
[  289s] Traceback (most recent call last):
[  289s]   File "/usr/lib64/python3.8/logging/__init__.py", line 1088, in emit
[  289s]     stream.write(msg + self.terminator)
[  289s] ValueError: I/O operation on closed file.
[  289s] Call stack:
[  289s]   File "/usr/lib/python3.8/site-packages/jupyter_client/client.py", line 128, in __del__
[  289s]     self.log.debug("Destroying zmq context for %s", self)
[  289s] Message: 'Destroying zmq context for %s'
[  289s] Arguments: (<jupyter_client.asynchronous.client.AsyncKernelClient object at 0x7fec916f30a0>,)
[  289s] Task was destroyed but it is pending!
[  289s] task: <Task pending name='Task-367' coro=<RequestHandler._execute() running at /usr/lib64/python3.8/site-packages/tornado/web.py:1713> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fec8b35ab80>()]> cb=[_HandlerDelegate.execute.<locals>.<lambda>() at /usr/lib64/python3.8/site-packages/tornado/web.py:2361]>
[  289s] --- Logging error ---
[  289s] Traceback (most recent call last):
[  289s]   File "/usr/lib64/python3.8/logging/__init__.py", line 1088, in emit
[  289s]     stream.write(msg + self.terminator)
[  289s] ValueError: I/O operation on closed file.
[  289s] Call stack:
[  289s]   File "/usr/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 122, in __del__
[  289s]     self.log.debug("Destroying zmq context for %s", self)
[  289s] Message: 'Destroying zmq context for %s'
[  289s] Arguments: (<jupyter_server.services.kernels.kernelmanager.AsyncMappingKernelManager object at 0x7fec92008f70>,)
[  289s] ++ '[' -f _current_flavor ']'
[  289s] ++ cat _current_flavor
[  289s] + last_flavor=python38
[  289s] + '[' -z python38 ']'
[  289s] + '[' python38 '!=' python39 ']'
[  289s] + '[' -d build ']'
[  289s] + mv build _build.python38
[  289s] + '[' -d _build.python39 ']'
[  289s] + mv _build.python39 build
[  289s] + echo python39
[  289s] + python_flavor=python39
[  289s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-voila-test-0.4.0-66.1.x86_64/usr/lib/python3.9/site-packages
[  289s] + PYTHONDONTWRITEBYTECODE=1
[  289s] + pytest-3.9 --ignore=_build.python38 --ignore=_build.python39 --ignore=_build.python310 -v tests -k 'not (test_kernel_death or test_request_with_query)' --reruns 2 --reruns-delay 1
[  290s] ============================= test session starts ==============================
[  290s] platform linux -- Python 3.9.16, pytest-7.1.2, pluggy-1.0.0 -- /usr/bin/python3.9
[  290s] cachedir: .pytest_cache
[  290s] rootdir: /home/abuild/rpmbuild/BUILD/voila-0.4.0
[  290s] plugins: anyio-3.6.2, rerunfailures-10.2, tornasync-0.6.0.post2
[  292s] collecting ... collected 73 items / 6 deselected / 67 selected
[  292s] 
[ 5699s] tests/execute_output_test.py::test_execute_output qemu-kvm: terminating on signal 15 from pid 20538 ()
[ 5699s] ### VM INTERACTION END ###
[ 5699s] No buildstatus set, either the base system is broken (kernel/initrd/udev/glibc/bash/perl)
[ 5699s] or the build host has a kernel or hardware problem...
```

**Comment by martinRenou** [comment]
Fixed since https://github.com/voila-dashboards/voila/pull/1308
