### ISSUE TITLE
Add option to list available templates?

### ISSUE THREAD

**Issue by cdeil** [voila-dashboards/voila#511]
I think it would be nice to have an option to list available templates.

Currently the docs have this: https://voila.readthedocs.io/en/stable/customize.html#where-are-voila-templates-located

And the command if I try some template that doesn't exist is this:
```
% voila workshop.ipynb --template=spamalot
Traceback (most recent call last):
  File "/Users/deil/opt/anaconda3/envs/voila-starter-pack/bin/voila", line 10, in <module>
    sys.exit(main())
  File "/Users/deil/opt/anaconda3/envs/voila-starter-pack/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "/Users/deil/opt/anaconda3/envs/voila-starter-pack/lib/python3.7/site-packages/voila/app.py", line 348, in initialize
    self.setup_template_dirs()
  File "/Users/deil/opt/anaconda3/envs/voila-starter-pack/lib/python3.7/site-packages/voila/app.py", line 357, in setup_template_dirs
    self.voila_configuration.template)
  File "/Users/deil/opt/anaconda3/envs/voila-starter-pack/lib/python3.7/site-packages/voila/paths.py", line 83, in collect_template_paths
    raise ValueError('No template sub-directory with name %r found in the following paths:\n\t%s' % (template_name, paths))
ValueError: No template sub-directory with name 'spamalot' found in the following paths:
	/Users/deil/Library/Jupyter/voila/templates
	/Users/deil/opt/anaconda3/envs/voila-starter-pack/share/jupyter/voila/templates
	/usr/local/share/jupyter/voila/templates
	/usr/share/jupyter/voila/templates
```

I could look around those folder. But it would be nice to have something like this available:
```
voila --list-templates
```

You know, like how `conda env list` lists available envs.

cc @jtpio

**Comment by jtpio** [comment]
Thanks @cdeil for opening this, and indeed it would be really useful!

Parts of that were implemented in https://github.com/voila-dashboards/voila/pull/201, so the template could be chosen from a URL parameter. But this PR needs to be rebased / redone when the [new template system](https://github.com/voila-dashboards/voila/pull/208) gets in.
