### ISSUE TITLE
Voila Won't Start - cannot import name ConverterMapping

### ISSUE THREAD

**Issue by phillc73** [voila-dashboards/voila#518]
System is a fresh Debian 10.

Voila was installed successfully with pip
```
phill@debian10:~$ pip install --user voila
Collecting voila
  Downloading https://files.pythonhosted.org/packages/82/50/191abf9f09817c2725c9f6542c812aa80ea090bf5fa3ad82fa7b918e55d7/voila-0.1.18-py2.py3-none-any.whl (5.9MB)
    100% |████████████████████████████████| 5.9MB 197kB/s
Collecting jupyter-server<0.2.0,>=0.1.0 (from voila)
  Downloading https://files.pythonhosted.org/packages/0f/9e/4b5bddfbab2f56b561b672d04c300d6c2d4b3f2c7c99e7935892104f2efa/jupyter_server-0.1.1-py2.py3-none-any.whl (183kB)
    100% |████████████████████████████████| 184kB 1.8MB/s
Requirement already satisfied: nbconvert<6,>=5.6.0 in ./.local/lib/python2.7/site-packages (from voila) (5.6.1)
Requirement already satisfied: pygments<3,>=2.4.1 in ./.local/lib/python2.7/site-packages (from voila) (2.5.2)
Collecting jupyterlab-pygments<0.2,>=0.1.0 (from voila)
  Using cached https://files.pythonhosted.org/packages/d8/4d/579c4613dbc656c07fa424663818f8bddd77ecafe6956497f66cab82b130/jupyterlab_pygments-0.1.0-py2.py3-none-any.whl
Requirement already satisfied: ipykernel in ./.local/lib/python2.7/site-packages (from jupyter-server<0.2.0,>=0.1.0->voila) (4.10.1)
Requirement already satisfied: traitlets>=4.2.1 in ./.local/lib/python2.7/site-packages (from jupyter-server<0.2.0,>=0.1.0->voila) (4.3.3)
Requirement already satisfied: jupyter-core>=4.4.0 in ./.local/lib/python2.7/site-packages (from jupyter-server<0.2.0,>=0.1.0->voila) (4.6.1)
Requirement already satisfied: jupyter-client>=5.3.1 in ./.local/lib/python2.7/site-packages (from jupyter-server<0.2.0,>=0.1.0->voila) (5.3.4)
Requirement already satisfied: tornado>=4 in ./.local/lib/python2.7/site-packages (from jupyter-server<0.2.0,>=0.1.0->voila) (5.1.1)
Requirement already satisfied: Send2Trash in ./.local/lib/python2.7/site-packages (from jupyter-server<0.2.0,>=0.1.0->voila) (1.5.0)
Requirement already satisfied: jinja2 in ./.local/lib/python2.7/site-packages (from jupyter-server<0.2.0,>=0.1.0->voila) (2.10.3)
Requirement already satisfied: prometheus-client in ./.local/lib/python2.7/site-packages (from jupyter-server<0.2.0,>=0.1.0->voila) (0.7.1)
Requirement already satisfied: pyzmq>=17 in ./.local/lib/python2.7/site-packages (from jupyter-server<0.2.0,>=0.1.0->voila) (18.1.1)
Requirement already satisfied: terminado>=0.8.1 in ./.local/lib/python2.7/site-packages (from jupyter-server<0.2.0,>=0.1.0->voila) (0.8.3)
Requirement already satisfied: ipython-genutils in ./.local/lib/python2.7/site-packages (from jupyter-server<0.2.0,>=0.1.0->voila) (0.2.0)
Requirement already satisfied: nbformat in ./.local/lib/python2.7/site-packages (from jupyter-server<0.2.0,>=0.1.0->voila) (5.0.3)
Requirement already satisfied: ipaddress; python_version == "2.7" in /usr/lib/python2.7/dist-packages (from jupyter-server<0.2.0,>=0.1.0->voila) (1.0.17)
Requirement already satisfied: bleach in ./.local/lib/python2.7/site-packages (from nbconvert<6,>=5.6.0->voila) (3.1.0)
Requirement already satisfied: mistune<2,>=0.8.1 in ./.local/lib/python2.7/site-packages (from nbconvert<6,>=5.6.0->voila) (0.8.4)
Requirement already satisfied: testpath in ./.local/lib/python2.7/site-packages (from nbconvert<6,>=5.6.0->voila) (0.4.4)
Requirement already satisfied: defusedxml in ./.local/lib/python2.7/site-packages (from nbconvert<6,>=5.6.0->voila) (0.6.0)
Requirement already satisfied: pandocfilters>=1.4.1 in ./.local/lib/python2.7/site-packages (from nbconvert<6,>=5.6.0->voila) (1.4.2)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/lib/python2.7/dist-packages (from nbconvert<6,>=5.6.0->voila) (0.3)
Requirement already satisfied: ipython>=4.0.0 in ./.local/lib/python2.7/site-packages (from ipykernel->jupyter-server<0.2.0,>=0.1.0->voila) (5.8.0)
Requirement already satisfied: decorator in ./.local/lib/python2.7/site-packages (from traitlets>=4.2.1->jupyter-server<0.2.0,>=0.1.0->voila) (4.4.1)
Requirement already satisfied: enum34; python_version == "2.7" in /usr/lib/python2.7/dist-packages (from traitlets>=4.2.1->jupyter-server<0.2.0,>=0.1.0->voila) (1.1.6)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from traitlets>=4.2.1->jupyter-server<0.2.0,>=0.1.0->voila) (1.12.0)
Requirement already satisfied: python-dateutil>=2.1 in ./.local/lib/python2.7/site-packages (from jupyter-client>=5.3.1->jupyter-server<0.2.0,>=0.1.0->voila) (2.8.1)
Requirement already satisfied: backports-abc>=0.4 in ./.local/lib/python2.7/site-packages (from tornado>=4->jupyter-server<0.2.0,>=0.1.0->voila) (0.5)
Requirement already satisfied: singledispatch in ./.local/lib/python2.7/site-packages (from tornado>=4->jupyter-server<0.2.0,>=0.1.0->voila) (3.4.0.3)
Requirement already satisfied: futures in ./.local/lib/python2.7/site-packages (from tornado>=4->jupyter-server<0.2.0,>=0.1.0->voila) (3.3.0)
Requirement already satisfied: MarkupSafe>=0.23 in ./.local/lib/python2.7/site-packages (from jinja2->jupyter-server<0.2.0,>=0.1.0->voila) (1.1.1)
Requirement already satisfied: ptyprocess; os_name != "nt" in ./.local/lib/python2.7/site-packages (from terminado>=0.8.1->jupyter-server<0.2.0,>=0.1.0->voila) (0.6.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in ./.local/lib/python2.7/site-packages (from nbformat->jupyter-server<0.2.0,>=0.1.0->voila) (3.2.0)
Requirement already satisfied: webencodings in ./.local/lib/python2.7/site-packages (from bleach->nbconvert<6,>=5.6.0->voila) (0.5.1)
Requirement already satisfied: pickleshare in ./.local/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->jupyter-server<0.2.0,>=0.1.0->voila) (0.7.5)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in ./.local/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->jupyter-server<0.2.0,>=0.1.0->voila) (1.0.18)
Requirement already satisfied: backports.shutil-get-terminal-size; python_version == "2.7" in ./.local/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->jupyter-server<0.2.0,>=0.1.0->voila) (1.0.0)
Requirement already satisfied: setuptools>=18.5 in /usr/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel->jupyter-server<0.2.0,>=0.1.0->voila) (40.8.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in ./.local/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->jupyter-server<0.2.0,>=0.1.0->voila) (4.7.0)
Requirement already satisfied: pathlib2; python_version == "2.7" or python_version == "3.3" in ./.local/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->jupyter-server<0.2.0,>=0.1.0->voila) (2.3.5)
Requirement already satisfied: simplegeneric>0.8 in ./.local/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel->jupyter-server<0.2.0,>=0.1.0->voila) (0.8.1)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in ./.local/lib/python2.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupyter-server<0.2.0,>=0.1.0->voila) (1.4.0)
Requirement already satisfied: attrs>=17.4.0 in ./.local/lib/python2.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupyter-server<0.2.0,>=0.1.0->voila) (19.3.0)
Requirement already satisfied: functools32; python_version < "3" in ./.local/lib/python2.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupyter-server<0.2.0,>=0.1.0->voila) (3.2.3.post2)
Requirement already satisfied: pyrsistent>=0.14.0 in ./.local/lib/python2.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupyter-server<0.2.0,>=0.1.0->voila) (0.15.7)
Requirement already satisfied: wcwidth in ./.local/lib/python2.7/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipykernel->jupyter-server<0.2.0,>=0.1.0->voila) (0.1.8)
Requirement already satisfied: scandir; python_version < "3.5" in ./.local/lib/python2.7/site-packages (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython>=4.0.0->ipykernel->jupyter-server<0.2.0,>=0.1.0->voila) (1.10.0)
Requirement already satisfied: configparser>=3.5; python_version < "3" in ./.local/lib/python2.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat->jupyter-server<0.2.0,>=0.1.0->voila) (4.0.2)
Requirement already satisfied: contextlib2; python_version < "3" in ./.local/lib/python2.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat->jupyter-server<0.2.0,>=0.1.0->voila) (0.6.0.post1)
Requirement already satisfied: zipp>=0.5 in ./.local/lib/python2.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat->jupyter-server<0.2.0,>=0.1.0->voila) (1.0.0)
Requirement already satisfied: more-itertools in ./.local/lib/python2.7/site-packages (from zipp>=0.5->importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat->jupyter-server<0.2.0,>=0.1.0->voila) (5.0.0)
Installing collected packages: jupyter-server, jupyterlab-pygments, voila
Successfully installed jupyter-server-0.1.1 jupyterlab-pygments-0.1.0 voila-0.1.18
```

Starting `Voila` standalone returns the following error:

```
phill@debian10:~$ voila
Traceback (most recent call last):
  File "/home/phill/.local/bin/voila", line 6, in <module>
    from voila.app import main
  File "/home/phill/.local/lib/python2.7/site-packages/voila/__init__.py", line 11, in <module>
    from .server_extension import load_jupyter_server_extension  # noqa
  File "/home/phill/.local/lib/python2.7/site-packages/voila/server_extension.py", line 20, in <module>
    from .handler import VoilaHandler
  File "/home/phill/.local/lib/python2.7/site-packages/voila/handler.py", line 19, in <module>
    from nbconvert.preprocessors import ClearOutputPreprocessor
  File "/home/phill/.local/lib/python2.7/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/home/phill/.local/lib/python2.7/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
    from .base import (export, get_exporter,
  File "/home/phill/.local/lib/python2.7/site-packages/nbconvert/exporters/base.py", line 8, in <module>
    import entrypoints
  File "/usr/lib/python2.7/dist-packages/entrypoints.py", line 16, in <module>
    import configparser
  File "/home/phill/.local/lib/python2.7/site-packages/configparser.py", line 11, in <module>
    from backports.configparser import (
ImportError: cannot import name ConverterMapping
```

Have to admit I'm new to Jupyter and Python in general, although experienced with other languages (R, Julia) and have reasonable Debian Server Ops experience. Apologies if I'm missing something straightforward.

**Comment by phillc73** [comment]
I think the problem here is multiple versions of Python and the default being Python 2.7, which Voila doesn't like very much.

Install pip for Python 3 and then install Voila with pip:

```
apt-get install python3-pip

python3 -m pip install --user voila

```

Voila will then launch as a stand alone application.
