### ISSUE TITLE
Voila raises NotImplementedError on Python 3.8 windows

### ISSUE THREAD

**Issue by ruoyu0088** [voila-dashboards/voila#583]
Here is the error message, it seems the same as https://github.com/jupyter/notebook/issues/5094

```
Traceback (most recent call last):
  File "C:\Miniconda38\Scripts\voila-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Miniconda38\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Miniconda38\lib\site-packages\voila\app.py", line 509, in start
    self.listen()
  File "C:\Miniconda38\lib\site-packages\voila\app.py", line 529, in listen
    self.app.listen(port)
  File "C:\Miniconda38\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "C:\Miniconda38\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Miniconda38\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Miniconda38\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Miniconda38\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Miniconda38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

**Comment by TristanK27** [comment]
I also have the same problem with python version 3.8.3.
The fix mentioned in [#5094](https://github.com/jupyter/notebook/issues/5094#issuecomment-560051955_) fixed the issue for me.
