### ISSUE TITLE
[master] nbconvert errors in the base template

### ISSUE THREAD

**Issue by SylvainCorlay** [voila-dashboards/voila#600]
I am seeing the following exception when using voilà master

```
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/voila/handler.py", line 107, in get
    async for html_snippet, resources in self.exporter.generate_from_notebook_node(self.notebook, resources=resources, extra_context=extra_context):
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/voila/exporter.py", line 102, in generate_from_notebook_node
    async for output in self.template.generate_async(nb=nb_copy, resources=resources, **extra_context):
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 35, in generate_async
    yield self.environment.handle_exception()
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/sylvain/miniconda3/share/jupyter/voila/templates/default/nbconvert_templates/voila.tpl", line 2, in top-level template code
    {% import "spinner.tpl" as spinner %}
  File "/home/sylvain/miniconda3/share/jupyter/voila/templates/default/nbconvert_templates/base.tpl", line 1, in top-level template code
    {%- extends 'lab.tpl' -%}
  File "/home/sylvain/miniconda3/share/jupyter/voila/templates/default/nbconvert_templates/lab.tpl", line 223, in top-level template code
    {% set div_id = uuid4() %}
  File "/home/sylvain/miniconda3/share/jupyter/nbconvert/templates/compatibility/display_priority.tpl", line 1, in top-level template code
    {%- extends 'base/display_priority.j2' -%}
  File "/home/sylvain/miniconda3/share/jupyter/nbconvert/templates/base/display_priority.j2", line 1, in top-level template code
    {%- extends 'null.j2' -%}
  File "/home/sylvain/miniconda3/share/jupyter/nbconvert/templates/base/null.j2", line 26, in top-level template code
    {%- block body -%}
  File "/home/sylvain/miniconda3/share/jupyter/voila/templates/default/nbconvert_templates/voila.tpl", line 63, in block "body"
    {%- block body_loop -%}
  File "/home/sylvain/miniconda3/share/jupyter/voila/templates/default/nbconvert_templates/voila.tpl", line 82, in block "body_loop"
    {%- block any_cell scoped -%}
  File "/home/sylvain/miniconda3/share/jupyter/voila/templates/default/nbconvert_templates/voila.tpl", line 84, in block "any_cell"
    {{ super() }}
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 174, in auto_await
    return await value
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 25, in concat_async
    await collect()
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 22, in collect
    async for event in async_gen:
  File "/home/sylvain/miniconda3/share/jupyter/nbconvert/templates/base/null.j2", line 95, in block "any_cell"
    {%- if resources.global_content_filter.include_unknown and not cell.get("transient",{}).get("remove_source", false) -%}
jinja2.exceptions.UndefinedError: 'tuple object' has no attribute 'get'
```

**Comment by SylvainCorlay** [comment]
This error seems to occur when there is an execution error in a cell.

**Comment by jtpio** [comment]
Closing as fixed, as the error:

```
jinja2.exceptions.UndefinedError: 'tuple object' has no attribute 'get'
``` 

doesn't show up anymore when there is an cell execution error.
