### ISSUE TITLE
Heroku deployment fails

### ISSUE THREAD

**Issue by adriaan** [voila-dashboards/voila#660]
When following the instructions from https://voila.readthedocs.io/en/stable/deploy.html to deploy Voilà on Heroku, I get the following crash:

```
2020-07-23T13:48:30.000000+00:00 app[api]: Build succeeded
2020-07-23T13:48:31.754827+00:00 app[web.1]: Traceback (most recent call last):
2020-07-23T13:48:31.754855+00:00 app[web.1]:   File "/app/.heroku/python/bin/voila", line 8, in <module>
2020-07-23T13:48:31.755010+00:00 app[web.1]:     sys.exit(main())
2020-07-23T13:48:31.755035+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
2020-07-23T13:48:31.755539+00:00 app[web.1]:     app.initialize(argv)
2020-07-23T13:48:31.755563+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/voila/app.py", line 342, in initialize
2020-07-23T13:48:31.755943+00:00 app[web.1]:     raise ValueError('provided more than 1 argument: %r' % self.extra_args)
2020-07-23T13:48:31.756009+00:00 app[web.1]: ValueError: provided more than 1 argument: ['—-port=25904', '—-no-browser', 'notebook.ipynb']
2020-07-23T13:48:31.917834+00:00 heroku[web.1]: Process exited with status 1
2020-07-23T13:48:31.965976+00:00 heroku[web.1]: State changed from starting to crashed
```

My Procfile is:
```
web: voila —-port=$PORT —-no-browser notebook.ipynb
```

Has something changed recently and are the deployment instructions out of date, or am I missing something?

**Comment by martinRenou** [comment]
Your options have a weird extra dash in front of them: It should not be `—-port` but `--port`

**Comment by adriaan** [comment]
Well spotted @martinRenou and thanks for the quick response. No idea how that happened... All good now.
