### ISSUE TITLE
The Voilà endpoint on mybinder.org returns "404 not found"

### ISSUE THREAD

**Issue by paloha** [voila-dashboards/voila#895]
Over a year ago I deployed a Jupyer Notebook based Voilà app on Heroku. I also wanted the users to have the possibility of running it on mybinder.org. So based on the Voilà [deployment guide][1] I have adjusted my [GitLab repo][2] and using the [mybinder.org][3] page I have created the binder link. I have tested it and all worked well. Today, after approx. a year, I needed to run the app on Binder and I got a 404 error. To manually debug what happened I have run a terminal in that instance of binder and tried running `voila /webapp/webapp.ipynb` and I got the following error:

```
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/voila", line 8, in <module>
    sys.exit(main())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/voila/app.py", line 370, in initialize
    self.setup_template_dirs()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/voila/app.py", line 376, in setup_template_dirs
    self.template_paths = collect_template_paths(['voila', 'nbconvert'], template_name, prune=True)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/voila/paths.py", line 24, in collect_template_paths
    return collect_paths(app_names, template_name, include_root_paths=True, prune=prune, root_dirs=root_dirs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/voila/paths.py", line 53, in collect_paths
    root_dirs = root_dirs or _default_root_dirs()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/voila/paths.py", line 102, in _default_root_dirs
    if nbconvert.exporters.templateexporter.DEV_MODE:
AttributeError: module 'nbconvert.exporters.templateexporter' has no attribute 'DEV_MODE'
```

It seems the error is caused by the line 102 in the file [voila/paths.py](https://github.com/voila-dashboards/voila/blob/master/voila/paths.py), because calling `nbconvert.exporters.templateexporter.DEV_MODE` returns the aforementioned error. This code was introduced in the `Voilà v0.2.0a0` released on 28 May 2020. Downgrading with `pip install -I voila==0.1.22` and visiting the `/voila/render/webapp/webapp.ipynb` endpoint does not resolve the issue. Even though running the voila directly with `voila webapp/webapp.ipynb` seems to work:

```
[Voila] Using /tmp to store connection files
[Voila] Storing connection files in /tmp/voila_da_qme55.
[Voila] Serving static files from /srv/conda/envs/notebook/lib/python3.7/site-packages/voila/static.
[Voila] Voila is running at:
http://localhost:8866/
[Voila] WARNING | No web browser found: could not locate runnable browser.
```
Do you please have any idea how to resolve this? 
Thank you very much.

  [1]: https://voila.readthedocs.io/en/stable/deploy.html#deployment-on-binder
  [2]: https://gitlab.com/hararticles/group-testing-simulations
  [3]: https://mybinder.org/

**Comment by paloha** [comment]
I have tried to run my project again locally today, I let pip to install the newest dependencies, then I pip freezed the versions it chose and I tried to run the project as such on binder and it worked. :tada:

I am not sure which dependency was causing the problem but it is all working now and I hope it was just a problem of me being sloppy and not locking the versions in my `requirements.txt`.
